### ISSUE TITLE
Commands not being executed

### ISSUE THREAD

**Issue by YasienDwieb** [dokku/dokku-api#5]
I am using postman to make requests to dokku api but the {result data:null} is always appearing.
sometimes I supply invalid api keys but I never get "not authenticated" message.
I made sure that dokku-daemon is running and mount is done
dokku-daemon.sock file already checked for existence 
I get no errors but no commands being executed.

**Comment by beydogan** [comment]
Can you create a gist with the api's logs please? Something like; `dokku logs dokku-api -n 1000`.

**Comment by beydogan** [comment]
@YasienDwieb any updates on this?

**Comment by YasienDwieb** [comment]
sorry for not replying but we are now using another method to implement api.
Thanks for attention.

**Comment by felixcheruiyot** [comment]
@beydogan Same problem here.
My logs don't show anything unusual:
 `2017-09-19T10:51:10.307630528Z app[web.1]: [1] Puma starting in cluster mode...
2017-09-19T10:51:10.307715522Z app[web.1]: [1] * Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
2017-09-19T10:51:10.308040273Z app[web.1]: [1] * Min threads: 1, max threads: 16
2017-09-19T10:51:10.308061145Z app[web.1]: [1] * Environment: development
2017-09-19T10:51:10.308073225Z app[web.1]: [1] * Process workers: 4
2017-09-19T10:51:10.308083317Z app[web.1]: [1] * Phased restart available
2017-09-19T10:51:10.308498859Z app[web.1]: [1] * Listening on tcp://0.0.0.0:5000
2017-09-19T10:51:10.309125646Z app[web.1]: [1] Use Ctrl-C to stop
2017-09-19T10:51:12.848296222Z app[web.1]: [1] - Worker 1 (pid: 12) booted, phase: 0
2017-09-19T10:51:12.936888177Z app[web.1]: [1] - Worker 0 (pid: 8) booted, phase: 0
2017-09-19T10:51:12.989071544Z app[web.1]: [1] - Worker 2 (pid: 15) booted, phase: 0
2017-09-19T10:51:13.038178419Z app[web.1]: [1] - Worker 3 (pid: 18) booted, phase: 0`

@YasienDwieb which other method are you using? Can you recommend?

**Comment by beydogan** [comment]
I forgot to include steps to scale the worker process in Readme.

Running following should fix the issue:
`dokku ps:scale dokku-api worker=1 `

**Comment by babarinde** [comment]
Hi,
When i execute the commands and try to retrieve it, i get this error
`"result_data": {
        "ok": false,
        "output": "No such file or directory - connect(2) for /var/run/dokku-daemon/dokku-daemon.sock"
    }`
logs look like this
``2018-01-25T08:31:35.777862824Z app[worker.1]: 9 TID-gr85h7m6c INFO: Booting Sidekiq 4.2.9 with redis options {:url=>"redis://dokku-api:REDACTED@dokku-redis-dokku-api:6379"}
2018-01-25T08:31:35.956234681Z app[worker.1]: 9 TID-gr85h7m6c INFO: Booting Sidekiq 4.2.9 with redis options {:url=>"redis://dokku-api:REDACTED@dokku-redis-dokku-api:6379"}
2018-01-25T08:31:35.957267613Z app[worker.1]: 9 TID-gr85h7m6c INFO: Running in ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
2018-01-25T08:31:35.957342938Z app[worker.1]: 9 TID-gr85h7m6c INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-01-25T08:31:35.957352243Z app[worker.1]: 9 TID-gr85h7m6c INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-01-25T08:31:36.014649355Z app[worker.1]: 9 TID-gr85h7m6c DEBUG: Client Middleware: 
2018-01-25T08:31:36.014678411Z app[worker.1]: 9 TID-gr85h7m6c DEBUG: Server Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::RetryJobs
2018-01-25T08:31:36.014683250Z app[worker.1]: 9 TID-gr85h7m6c INFO: Starting processing, hit Ctrl-C to stop
2018-01-25T08:31:36.014686772Z app[worker.1]: 9 TID-gr85h7m6c DEBUG: {:queues=>["default"], :labels=>[], :concurrency=>1, :require=>"./workers/command_runner.rb", :environment=>nil, :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x0055fc6f55a0c0>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x0055fc6f500b38@/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35>, :executor=>#<Proc:0x0055fc6f500b10@/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36>, :verbose=>true, :pidfile=>"./sidekiq.pid", :config_file=>"./config/sidekiq.yml", :strict=>true, :identity=>"worker.1:9:34158f697291"}
2018-01-25T10:16:43.402413209Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-1a712449499920112f50dcb8 INFO: start
2018-01-25T10:16:43.426765398Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-1a712449499920112f50dcb8 INFO: [CommandRunner] 1
2018-01-25T10:16:43.495323031Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-1a712449499920112f50dcb8 INFO: [CommandRunner] Exception
2018-01-25T10:16:43.519464838Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-1a712449499920112f50dcb8 INFO: No such file or directory - connect(2) for /var/run/dokku-daemon/dokku-daemon.sock
2018-01-25T10:16:43.535105020Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-1a712449499920112f50dcb8 INFO: done: 0.127 sec
2018-01-25T10:19:31.532578812Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-327b39af0e868a536cff797b INFO: start
2018-01-25T10:19:31.532901509Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-327b39af0e868a536cff797b INFO: [CommandRunner] 2
2018-01-25T10:19:31.585946036Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-327b39af0e868a536cff797b INFO: [CommandRunner] Exception
2018-01-25T10:19:31.585987640Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-327b39af0e868a536cff797b INFO: No such file or directory - connect(2) for /var/run/dokku-daemon/dokku-daemon.sock
2018-01-25T10:19:31.602345178Z app[worker.1]: 9 TID-gr85oj9ck CommandRunner JID-327b39af0e868a536cff797b INFO: done: 0.071 sec
root@paas2:~# 2018-01-25T08:31:18.771699935Z app[web.1]: [9] Puma starting in cluster mode...
2018-01-25T08:31:18.780820912Z app[web.1]: [9] * Version 3.9.1 (ruby 2.3.4-p301), codename: Private Caller
2018-01-25T08:31:18.780870574Z app[web.1]: [9] * Min threads: 1, max threads: 4
2018-01-25T08:31:18.780876206Z app[web.1]: [9] * Environment: development
2018-01-25T08:31:18.780879650Z app[web.1]: [9] * Process workers: 2
2018-01-25T08:31:18.780882888Z app[web.1]: [9] * Phased restart available
2018-01-25T08:31:18.780886314Z app[web.1]: [9] * Listening on tcp://0.0.0.0:5000
2018-01-25T08:31:18.780890235Z app[web.1]: [9] Use Ctrl-C to stop
2018-01-25T08:31:20.085633096Z app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:100:in `execute_non_query': ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index" (DataObjects::IntegrityError)
2018-01-25T08:31:20.086041014Z app[web.1]: DETAIL:  Key (typname, typnamespace)=(keys_id_seq, 2200) already exists.
2018-01-25T08:31:20.122027663Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:100:in `block (2 levels) in create_model_storage'
2018-01-25T08:31:20.122083849Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:98:in `each'
2018-01-25T08:31:20.122098678Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:98:in `block in create_model_storage'
2018-01-25T08:31:20.122110297Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
2018-01-25T08:31:20.122121616Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:93:in `create_model_storage'
2018-01-25T08:31:20.122132894Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:23:in `block in create_model_storage'
2018-01-25T08:31:20.122144078Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:58:in `without_notices'
2018-01-25T08:31:20.122156095Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:23:in `create_model_storage'
2018-01-25T08:31:20.122167502Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:57:in `upgrade_model_storage'
2018-01-25T08:31:20.122178562Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:18:in `block in upgrade_model_storage'
2018-01-25T08:31:20.122189307Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:58:in `without_notices'
2018-01-25T08:31:20.122200759Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:18:in `upgrade_model_storage'
2018-01-25T08:31:20.122213127Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:73:in `upgrade_model_storage'
2018-01-25T08:31:20.122232324Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:145:in `auto_upgrade!'
2018-01-25T08:31:20.122277387Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:47:in `block in repository_execute'
2018-01-25T08:31:20.122291900Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:64:in `block in each'
2018-01-25T08:31:20.122304324Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `block in each'
2018-01-25T08:31:20.122316159Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `block in each'
2018-01-25T08:31:20.122328269Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
2018-01-25T08:31:20.122339192Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
2018-01-25T08:31:20.122350884Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `each'
2018-01-25T08:31:20.122361799Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:63:in `each'
2018-01-25T08:31:20.122372604Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:46:in `repository_execute'
2018-01-25T08:31:20.122383835Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:27:in `auto_upgrade!'
2018-01-25T08:31:20.122394993Z app[web.1]: 	from /app/config/environment.rb:26:in `block in <top (required)>'
2018-01-25T08:31:20.122406021Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1411:in `configure'
2018-01-25T08:31:20.122416692Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1981:in `block (2 levels) in delegate'
2018-01-25T08:31:20.122427414Z app[web.1]: 	from /app/config/environment.rb:18:in `<top (required)>'
2018-01-25T08:31:20.122438680Z app[web.1]: 	from /app/app.rb:4:in `require'
2018-01-25T08:31:20.122449736Z app[web.1]: 	from /app/app.rb:4:in `<top (required)>'
2018-01-25T08:31:20.122460448Z app[web.1]: 	from config.ru:1:in `require'
2018-01-25T08:31:20.122470336Z app[web.1]: 	from config.ru:1:in `block in <main>'
2018-01-25T08:31:20.122481514Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
2018-01-25T08:31:20.122492039Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
2018-01-25T08:31:20.122503385Z app[web.1]: 	from config.ru:in `new'
2018-01-25T08:31:20.122513383Z app[web.1]: 	from config.ru:in `<main>'
2018-01-25T08:31:20.122524155Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
2018-01-25T08:31:20.122538777Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
2018-01-25T08:31:20.122550035Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
2018-01-25T08:31:20.122577869Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:313:in `load_rackup'
2018-01-25T08:31:20.122589520Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:242:in `app'
2018-01-25T08:31:20.122600370Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/runner.rb:148:in `app'
2018-01-25T08:31:20.122622544Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/runner.rb:155:in `start_server'
2018-01-25T08:31:20.122633652Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:261:in `worker'
2018-01-25T08:31:20.122644053Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
2018-01-25T08:31:20.122655031Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `fork'
2018-01-25T08:31:20.122666222Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
2018-01-25T08:31:20.122680164Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `times'
2018-01-25T08:31:20.122690400Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `spawn_workers'
2018-01-25T08:31:20.122700689Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:447:in `run'
2018-01-25T08:31:20.122710978Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
2018-01-25T08:31:20.122722284Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
2018-01-25T08:31:20.122732350Z app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
2018-01-25T08:31:20.122743804Z app[web.1]: 	from /app/vendor/bundle/bin/puma:17:in `load'
2018-01-25T08:31:20.122753956Z app[web.1]: 	from /app/vendor/bundle/bin/puma:17:in `<main>'
2018-01-25T08:31:20.291554331Z app[web.1]: [9] - Worker 1 (pid: 163) booted, phase: 0
2018-01-25T08:31:21.075423773Z app[web.1]: [9] - Worker 0 (pid: 169) booted, phase: 0

**Comment by babarinde** [comment]
Hi,
Please disregard above, the dokku daemon was not installed hence the issue
Thanks
